{
    "ENVELOPE": {
        "HEADER": {
            "TALLYREQUEST": "Import Data"
        },
        "BODY": {
            "IMPORTDATA": {
                "REQUESTDESC": {
                    "REPORTNAME": "All Masters",
                    "STATICVARIABLES": {
                        "SVCURRENTCOMPANY": "Flourish"
                    }
                },
                "REQUESTDATA": {
                    "TALLYMESSAGE": [
                        {
                            "CURRENCY": {
                                "GUID": "a282ccd7-4452-4ea6-8468-933b6012dabd-0000001d",
                                "MAILINGNAME": "INR",
                                "ORIGINALNAME": "₹",
                                "EXPANDEDSYMBOL": "INR",
                                "DECIMALSYMBOL": "paise",
                                "ISUPDATINGTARGETID": "No",
                                "ISDELETED": "No",
                                "ISSECURITYONWHENENTERED": "No",
                                "ASORIGINAL": "Yes",
                                "ISSUFFIX": "No",
                                "HASSPACE": "Yes",
                                "INMILLIONS": "No",
                                "ALTERID": 258,
                                "DECIMALPLACES": 2,
                                "DECIMALPLACESFORPRINTING": 2,
                                "DAILYSTDRATES.LIST": "",
                                "DAILYBUYINGRATES.LIST": "",
                                "DAILYSELLINGRATES.LIST": ""
                            }
                        },
                        {
                            "CURRENCY": {
                                "GUID": "a282ccd7-4452-4ea6-8468-933b6012dabd-0000001d",
                                "MAILINGNAME": "INR",
                                "ORIGINALNAME": "₹",
                                "EXPANDEDSYMBOL": "INR",
                                "DECIMALSYMBOL": "paise",
                                "ISUPDATINGTARGETID": "No",
                                "ISDELETED": "No",
                                "ISSECURITYONWHENENTERED": "No",
                                "ASORIGINAL": "Yes",
                                "ISSUFFIX": "No",
                                "HASSPACE": "Yes",
                                "INMILLIONS": "No",
                                "ALTERID": 258,
                                "DECIMALPLACES": 2,
                                "DECIMALPLACESFORPRINTING": 2,
                                "DAILYSTDRATES.LIST": "",
                                "DAILYBUYINGRATES.LIST": "",
                                "DAILYSELLINGRATES.LIST": ""
                            }
                        },
                        {
                            "GROUP": {
                                "GUID": "a282ccd7-4452-4ea6-8468-933b6012dabd-00000007",
                                "PARENT": "",
                                "GRPDEBITPARENT": "",
                                "GRPCREDITPARENT": "",
                                "ISBILLWISEON": "No",
                                "ISCOSTCENTRESON": "No",
                                "ISADDABLE": "No",
                                "ISUPDATINGTARGETID": "No",
                                "ISDELETED": "No",
                                "ISSECURITYONWHENENTERED": "No",
                                "ASORIGINAL": "Yes",
                                "ISSUBLEDGER": "No",
                                "ISREVENUE": "No",
                                "AFFECTSGROSSPROFIT": "No",
                                "ISDEEMEDPOSITIVE": "No",
                                "TRACKNEGATIVEBALANCES": "No",
                                "ISCONDENSED": "No",
                                "AFFECTSSTOCK": "No",
                                "ISGROUPFORLOANRCPT": "No",
                                "ISGROUPFORLOANPYMNT": "No",
                                "ISRATEINCLUSIVEVAT": "No",
                                "ISINVDETAILSENABLE": "No",
                                "SORTPOSITION": 70,
                                "ALTERID": 8,
                                "SERVICETAXDETAILS.LIST": "",
                                "VATDETAILS.LIST": "",
                                "SALESTAXCESSDETAILS.LIST": "",
                                "GSTDETAILS.LIST": "",
                                "HSNDETAILS.LIST": "",
                                "LANGUAGENAME.LIST": {
                                    "NAME.LIST": {
                                        "NAME": "Branch / Divisions"
                                    },
                                    "LANGUAGEID": 1033
                                },
                                "XBRLDETAIL.LIST": "",
                                "AUDITDETAILS.LIST": "",
                                "SCHVIDETAILS.LIST": "",
                                "EXCISETARIFFDETAILS.LIST": "",
                                "TCSCATEGORYDETAILS.LIST": "",
                                "TDSCATEGORYDETAILS.LIST": "",
                                "GSTCLASSFNIGSTRATES.LIST": "",
                                "EXTARIFFDUTYHEADDETAILS.LIST": "",
                                "TEMPGSTITEMSLABRATES.LIST": ""
                            }
                        },                       
                        {
                            "GROUP": {
                                "GUID": "a282ccd7-4452-4ea6-8468-933b6012dabd-0000000d",
                                "PARENT": "Loans (Liability)",
                                "GRPDEBITPARENT": "",
                                "GRPCREDITPARENT": "",
                                "ISBILLWISEON": "No",
                                "ISCOSTCENTRESON": "No",
                                "ISADDABLE": "No",
                                "ISUPDATINGTARGETID": "No",
                                "ISDELETED": "No",
                                "ISSECURITYONWHENENTERED": "No",
                                "ASORIGINAL": "Yes",
                                "ISSUBLEDGER": "No",
                                "ISREVENUE": "No",
                                "AFFECTSGROSSPROFIT": "No",
                                "ISDEEMEDPOSITIVE": "No",
                                "TRACKNEGATIVEBALANCES": "No",
                                "ISCONDENSED": "No",
                                "AFFECTSSTOCK": "No",
                                "ISGROUPFORLOANRCPT": "No",
                                "ISGROUPFORLOANPYMNT": "No",
                                "ISRATEINCLUSIVEVAT": "No",
                                "ISINVDETAILSENABLE": "No",
                                "SORTPOSITION": 130,
                                "ALTERID": 14,
                                "SERVICETAXDETAILS.LIST": "",
                                "VATDETAILS.LIST": "",
                                "SALESTAXCESSDETAILS.LIST": "",
                                "GSTDETAILS.LIST": "",
                                "HSNDETAILS.LIST": "",
                                "LANGUAGENAME.LIST": {
                                    "NAME.LIST": {
                                        "NAME": "Unsecured Loans"
                                    },
                                    "LANGUAGEID": 1033
                                },
                                "XBRLDETAIL.LIST": "",
                                "AUDITDETAILS.LIST": "",
                                "SCHVIDETAILS.LIST": "",
                                "EXCISETARIFFDETAILS.LIST": "",
                                "TCSCATEGORYDETAILS.LIST": "",
                                "TDSCATEGORYDETAILS.LIST": "",
                                "GSTCLASSFNIGSTRATES.LIST": "",
                                "EXTARIFFDUTYHEADDETAILS.LIST": "",
                                "TEMPGSTITEMSLABRATES.LIST": ""
                            }
                        },
                       
                        {
                            "LEDGER": {
                                "OLDAUDITENTRYIDS.LIST": {
                                    "OLDAUDITENTRYIDS": -1
                                },
                                "GUID": "a282ccd7-4452-4ea6-8468-933b6012dabd-000000dd",
                                "CURRENCYNAME": "₹",
                                "PRIORSTATENAME": "Gujarat",
                                "VATDEALERTYPE": "Regular",
                                "PARENT": "Sundry Creditors",
                                "TAXCLASSIFICATIONNAME": "&#4; Not Applicable",
                                "TAXTYPE": "Others",
                                "COUNTRYOFRESIDENCE": "India",
                                "LEDGERCOUNTRYISDCODE": 91,
                                "GSTTYPE": "&#4; Not Applicable",
                                "APPROPRIATEFOR": "&#4; Not Applicable",
                                "GSTNATUREOFSUPPLY": "&#4; Not Applicable",
                                "SERVICECATEGORY": "&#4; Not Applicable",
                                "EXCISELEDGERCLASSIFICATION": "&#4; Not Applicable",
                                "EXCISEDUTYTYPE": "&#4; Not Applicable",
                                "EXCISENATUREOFPURCHASE": "&#4; Not Applicable",
                                "LEDGERFBTCATEGORY": "&#4; Not Applicable",
                                "ISBILLWISEON": "Yes",
                                "ISCOSTCENTRESON": "No",
                                "ISINTERESTON": "No",
                                "ALLOWINMOBILE": "No",
                                "ISCOSTTRACKINGON": "No",
                                "ISBENEFICIARYCODEON": "No",
                                "ISEXPORTONVCHCREATE": "No",
                                "PLASINCOMEEXPENSE": "No",
                                "ISUPDATINGTARGETID": "No",
                                "ISDELETED": "No",
                                "ISSECURITYONWHENENTERED": "No",
                                "ASORIGINAL": "Yes",
                                "ISCONDENSED": "No",
                                "AFFECTSSTOCK": "No",
                                "ISRATEINCLUSIVEVAT": "No",
                                "FORPAYROLL": "No",
                                "ISABCENABLED": "No",
                                "ISCREDITDAYSCHKON": "No",
                                "INTERESTONBILLWISE": "No",
                                "OVERRIDEINTEREST": "No",
                                "OVERRIDEADVINTEREST": "No",
                                "USEFORVAT": "No",
                                "IGNORETDSEXEMPT": "No",
                                "ISTCSAPPLICABLE": "No",
                                "ISTDSAPPLICABLE": "No",
                                "ISFBTAPPLICABLE": "No",
                                "ISGSTAPPLICABLE": "No",
                                "ISEXCISEAPPLICABLE": "No",
                                "ISTDSEXPENSE": "No",
                                "ISEDLIAPPLICABLE": "No",
                                "ISRELATEDPARTY": "No",
                                "USEFORESIELIGIBILITY": "No",
                                "ISINTERESTINCLLASTDAY": "No",
                                "APPROPRIATETAXVALUE": "No",
                                "ISBEHAVEASDUTY": "No",
                                "INTERESTINCLDAYOFADDITION": "No",
                                "INTERESTINCLDAYOFDEDUCTION": "No",
                                "ISOTHTERRITORYASSESSEE": "No",
                                "IGNOREMISMATCHWITHWARNING": "No",
                                "USEASNOTIONALBANK": "No",
                                "BEHAVEASPAYMENTGATEWAY": "No",
                                "OVERRIDECREDITLIMIT": "No",
                                "ISAGAINSTFORMC": "No",
                                "ISCHEQUEPRINTINGENABLED": "Yes",
                                "ISPAYUPLOAD": "No",
                                "ISPAYBATCHONLYSAL": "No",
                                "ISBNFCODESUPPORTED": "No",
                                "ALLOWEXPORTWITHERRORS": "No",
                                "CONSIDERPURCHASEFOREXPORT": "No",
                                "ISTRANSPORTER": "No",
                                "ISECASHLEDGER": "No",
                                "USEFORNOTIONALITC": "No",
                                "ISECOMMOPERATOR": "No",
                                "OVERRIDEBASEDONREALIZATION": "No",
                                "ISECDIFFINSDATE": "No",
                                "SHOWINPAYSLIP": "No",
                                "USEFORGRATUITY": "No",
                                "ISTDSPROJECTED": "No",
                                "ISSALARYMULFILE": "No",
                                "FORSERVICETAX": "No",
                                "ISINPUTCREDIT": "No",
                                "ISEXEMPTED": "No",
                                "ISABATEMENTAPPLICABLE": "No",
                                "ISSTXPARTY": "No",
                                "ISSTXNONREALIZEDTYPE": "No",
                                "USEFORKKC": "No",
                                "USEFORSBC": "No",
                                "ISUSEDFORCVD": "No",
                                "LEDBELONGSTONONTAXABLE": "No",
                                "ISEXCISEMERCHANTEXPORTER": "No",
                                "ISPARTYEXEMPTED": "No",
                                "ISSEZPARTY": "No",
                                "TDSDEDUCTEEISSPECIALRATE": "No",
                                "ISECHEQUESUPPORTED": "No",
                                "ISEDDSUPPORTED": "No",
                                "HASECHEQUEDELIVERYMODE": "No",
                                "HASECHEQUEDELIVERYTO": "No",
                                "HASECHEQUEPRINTLOCATION": "No",
                                "HASECHEQUEPAYABLELOCATION": "No",
                                "HASECHEQUEBANKLOCATION": "No",
                                "HASEDDDELIVERYMODE": "No",
                                "HASEDDDELIVERYTO": "No",
                                "HASEDDPRINTLOCATION": "No",
                                "HASEDDPAYABLELOCATION": "No",
                                "HASEDDBANKLOCATION": "No",
                                "ISEBANKINGENABLED": "No",
                                "ISEXPORTFILEENCRYPTED": "No",
                                "ISBATCHENABLED": "No",
                                "ISPRODUCTCODEBASED": "No",
                                "HASEDDCITY": "No",
                                "HASECHEQUECITY": "No",
                                "ISFILENAMEFORMATSUPPORTED": "No",
                                "HASCLIENTCODE": "No",
                                "PAYINSISBATCHAPPLICABLE": "No",
                                "PAYINSISFILENUMAPP": "No",
                                "ISSALARYTRANSGROUPEDFORBRS": "No",
                                "ISEBANKINGSUPPORTED": "No",
                                "ISSCBUAE": "No",
                                "ISBANKSTATUSAPP": "No",
                                "ISSALARYGROUPED": "No",
                                "USEFORPURCHASETAX": "No",
                                "AUDITED": "No",
                                "SORTPOSITION": 1000,
                                "ALTERID": 255,
                                "SERVICETAXDETAILS.LIST": "",
                                "LBTREGNDETAILS.LIST": "",
                                "VATDETAILS.LIST": "",
                                "SALESTAXCESSDETAILS.LIST": "",
                                "GSTDETAILS.LIST": "",
                                "HSNDETAILS.LIST": "",
                                "MSMEREGISTRATIONDETAILS.LIST": "",
                                "LANGUAGENAME.LIST": {
                                    "NAME.LIST": {
                                        "NAME": "Vr"
                                    },
                                    "LANGUAGEID": 1033
                                },
                                "XBRLDETAIL.LIST": "",
                                "AUDITDETAILS.LIST": "",
                                "SCHVIDETAILS.LIST": "",
                                "EXCISETARIFFDETAILS.LIST": "",
                                "TCSCATEGORYDETAILS.LIST": "",
                                "TDSCATEGORYDETAILS.LIST": "",
                                "SLABPERIOD.LIST": "",
                                "GRATUITYPERIOD.LIST": "",
                                "ADDITIONALCOMPUTATIONS.LIST": "",
                                "EXCISEJURISDICTIONDETAILS.LIST": "",
                                "EXCLUDEDTAXATIONS.LIST": "",
                                "BANKALLOCATIONS.LIST": "",
                                "PAYMENTDETAILS.LIST": "",
                                "BANKEXPORTFORMATS.LIST": "",
                                "BILLALLOCATIONS.LIST": "",
                                "INTERESTCOLLECTION.LIST": "",
                                "LEDGERCLOSINGVALUES.LIST": "",
                                "LEDGERAUDITCLASS.LIST": "",
                                "OLDAUDITENTRIES.LIST": "",
                                "TDSEXEMPTIONRULES.LIST": "",
                                "DEDUCTINSAMEVCHRULES.LIST": "",
                                "LOWERDEDUCTION.LIST": "",
                                "STXABATEMENTDETAILS.LIST": "",
                                "LEDMULTIADDRESSLIST.LIST": "",
                                "STXTAXDETAILS.LIST": "",
                                "CHEQUERANGE.LIST": "",
                                "DEFAULTVCHCHEQUEDETAILS.LIST": "",
                                "ACCOUNTAUDITENTRIES.LIST": "",
                                "AUDITENTRIES.LIST": "",
                                "BRSIMPORTEDINFO.LIST": "",
                                "AUTOBRSCONFIGS.LIST": "",
                                "BANKURENTRIES.LIST": "",
                                "DEFAULTCHEQUEDETAILS.LIST": "",
                                "DEFAULTOPENINGCHEQUEDETAILS.LIST": "",
                                "CANCELLEDPAYALLOCATIONS.LIST": "",
                                "ECHEQUEPRINTLOCATION.LIST": "",
                                "ECHEQUEPAYABLELOCATION.LIST": "",
                                "EDDPRINTLOCATION.LIST": "",
                                "EDDPAYABLELOCATION.LIST": "",
                                "AVAILABLETRANSACTIONTYPES.LIST": "",
                                "LEDPAYINSCONFIGS.LIST": "",
                                "TYPECODEDETAILS.LIST": "",
                                "FIELDVALIDATIONDETAILS.LIST": "",
                                "INPUTCRALLOCS.LIST": "",
                                "TCSMETHODOFCALCULATION.LIST": "",
                                "LEDGSTREGDETAILS.LIST": {
                                    "APPLICABLEFROM": 20240401,
                                    "GSTREGISTRATIONTYPE": "Regular",
                                    "PLACEOFSUPPLY": "Gujarat",
                                    "ISOTHTERRITORYASSESSEE": "No",
                                    "CONSIDERPURCHASEFOREXPORT": "No",
                                    "ISTRANSPORTER": "No",
                                    "ISCOMMONPARTY": "No"
                                },
                                "LEDMAILINGDETAILS.LIST": {
                                    "APPLICABLEFROM": 20240401,
                                    "MAILINGNAME": "Vr",
                                    "STATE": "Gujarat",
                                    "COUNTRY": "India"
                                },
                                "GSTRECONPREFIXSUFFIXDETAILS.LIST": "",
                                "CONTACTDETAILS.LIST": {
                                    "NAME": "Primary Mobile No.",
                                    "COUNTRYISDCODE": 91,
                                    "ISDEFAULTWHATSAPPNUM": "Yes"
                                },
                                "GSTCLASSFNIGSTRATES.LIST": "",
                                "EXTARIFFDUTYHEADDETAILS.LIST": "",
                                "TEMPGSTITEMSLABRATES.LIST": "",
                                "VOUCHERTYPEPRODUCTCODES.LIST": "",
                                "LEDADDRESS.LIST": "",
                                "DEFMULTIPLETOPHONENO.LIST": ""
                            }
                        },
                        {
                            "COMPANY": {
                                "REMOTECMPINFO.LIST": {
                                    "NAME": "a282ccd7-4452-4ea6-8468-933b6012dabd",
                                    "REMOTECMPNAME": "Flourish",
                                    "REMOTECMPSTATE": "Gujarat"
                                }
                            }
                        }
                    ]
                }
            }
        }
    }
}