<TALLYMESSAGE xmlns:UDF="TallyUDF">
  <VOUCHER
    REMOTEID="1f926b40-de32-409c-b69c-9f0becd81ced"
    VCHKEY="a282ccd7-4452-4ea6-8468-933b6012dabd-0000b147:000000c8"
    VCHTYPE="Sales"
    ACTION="Create"
    OBJVIEW="Invoice Voucher View"
  >
    <OLDAUDITENTRYIDS.LIST TYPE="Number">
      <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
    </OLDAUDITENTRYIDS.LIST>
    <DATE>20240922</DATE>
    <VCHSTATUSDATE>20240922</VCHSTATUSDATE>
    <GUID>1f926b40-de32-409c-b69c-9f0becd81ced</GUID>
    <GSTREGISTRATIONTYPE>Regular</GSTREGISTRATIONTYPE>
    <VATDEALERTYPE>Regular</VATDEALERTYPE>
    <STATENAME>Gujarat</STATENAME>
    <COUNTRYOFRESIDENCE>India</COUNTRYOFRESIDENCE>
    <PLACEOFSUPPLY>Gujarat</PLACEOFSUPPLY>
    <PARTYNAME>Prime</PARTYNAME>
    <GSTREGISTRATION TAXTYPE="GST" TAXREGISTRATION="">
      Gujarat Registration
    </GSTREGISTRATION>
    <VOUCHERTYPENAME>Sales</VOUCHERTYPENAME>
    <PARTYLEDGERNAME>Prime</PARTYLEDGERNAME>
    <VOUCHERNUMBER>30</VOUCHERNUMBER>
    <BASICBUYERNAME>Prime</BASICBUYERNAME>
    <CMPGSTREGISTRATIONTYPE>Regular</CMPGSTREGISTRATIONTYPE>
    <PARTYMAILINGNAME>Prime</PARTYMAILINGNAME>
    <CONSIGNEEMAILINGNAME>Prime</CONSIGNEEMAILINGNAME>
    <CONSIGNEESTATENAME>Gujarat</CONSIGNEESTATENAME>
    <CMPGSTSTATE>Gujarat</CMPGSTSTATE>
    <CONSIGNEECOUNTRYNAME>India</CONSIGNEECOUNTRYNAME>
    <BASICBASEPARTYNAME>Prime</BASICBASEPARTYNAME>
    <NUMBERINGSTYLE>Auto Retain</NUMBERINGSTYLE>
    <CSTFORMISSUETYPE>Not Applicable</CSTFORMISSUETYPE>
    <CSTFORMRECVTYPE>Not Applicable</CSTFORMRECVTYPE>
    <FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
    <PERSISTEDVIEW>Invoice Voucher View</PERSISTEDVIEW>
    <VCHSTATUSTAXADJUSTMENT>Default</VCHSTATUSTAXADJUSTMENT>
    <VCHSTATUSVOUCHERTYPE>Sales</VCHSTATUSVOUCHERTYPE>
    <VCHGSTCLASS>Not Applicable</VCHGSTCLASS>
    <VCHENTRYMODE>Item Invoice</VCHENTRYMODE>
    <ALLINVENTORYENTRIES.LIST>
      <STOCKITEMNAME>Ro</STOCKITEMNAME>
      <GSTOVRDNISREVCHARGEAPPL>Not Applicable</GSTOVRDNISREVCHARGEAPPL>
      <GSTOVRDNSTOREDNATURE></GSTOVRDNSTOREDNATURE>
      <GSTOVRDNTYPEOFSUPPLY>Goods</GSTOVRDNTYPEOFSUPPLY>
      <GSTRATEINFERAPPLICABILITY>
        As per Masters/Company
      </GSTRATEINFERAPPLICABILITY>
      <GSTHSNINFERAPPLICABILITY>
        As per Masters/Company
      </GSTHSNINFERAPPLICABILITY>
      <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
      <RATE>111/Nos</RATE>
      <AMOUNT>1221</AMOUNT>
      <ACTUALQTY>11 Nos</ACTUALQTY>
      <BILLEDQTY>11 Nos</BILLEDQTY>
      <BATCHALLOCATIONS.LIST>
        <GODOWNNAME>Main Location</GODOWNNAME>
        <BATCHNAME>Primary Batch</BATCHNAME>
        <TRACKINGNUMBER>Not Applicable</TRACKINGNUMBER>
        <AMOUNT>1221</AMOUNT>
        <ACTUALQTY>11 Nos</ACTUALQTY>
        <BILLEDQTY>11 Nos</BILLEDQTY>
      </BATCHALLOCATIONS.LIST>
      <ACCOUNTINGALLOCATIONS.LIST>
        <LEDGERNAME>Sales Ledger</LEDGERNAME>
        <GSTCLASS>Not Applicable</GSTCLASS>
        <AMOUNT>1221</AMOUNT>
      </ACCOUNTINGALLOCATIONS.LIST>
    </ALLINVENTORYENTRIES.LIST>
    <LEDGERENTRIES.LIST>
      <OLDAUDITENTRYIDS.LIST TYPE="Number">
        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
      </OLDAUDITENTRYIDS.LIST>
      <LEDGERNAME>Prime</LEDGERNAME>
      <GSTCLASS>Not Applicable</GSTCLASS>
      <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
      <LEDGERFROMITEM>No</LEDGERFROMITEM>
      <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
      <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
      <GSTOVERRIDDEN>No</GSTOVERRIDDEN>
      <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
      <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
      <STRDGSTISPARTYLEDGER>No</STRDGSTISPARTYLEDGER>
      <STRDGSTISDUTYLEDGER>No</STRDGSTISDUTYLEDGER>
      <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
      <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
      <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
      <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
      <AMOUNT>-1221.00</AMOUNT>
      <SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST>
      <BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST>
      <BILLALLOCATIONS.LIST>
        <NAME>30</NAME>
        <BILLTYPE>New Ref</BILLTYPE>
        <TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE>
        <AMOUNT>-1221.00</AMOUNT>
        <INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST>
        <STBILLCATEGORIES.LIST></STBILLCATEGORIES.LIST>
      </BILLALLOCATIONS.LIST>
      <INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST>
      <OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST>
      <ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST>
      <AUDITENTRIES.LIST></AUDITENTRIES.LIST>
      <INPUTCRALLOCS.LIST></INPUTCRALLOCS.LIST>
      <DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST>
      <EXCISEDUTYHEADDETAILS.LIST></EXCISEDUTYHEADDETAILS.LIST>
      <RATEDETAILS.LIST></RATEDETAILS.LIST>
      <SUMMARYALLOCS.LIST></SUMMARYALLOCS.LIST>
      <CENVATDUTYALLOCATIONS.LIST></CENVATDUTYALLOCATIONS.LIST>
      <STPYMTDETAILS.LIST></STPYMTDETAILS.LIST>
      <EXCISEPAYMENTALLOCATIONS.LIST></EXCISEPAYMENTALLOCATIONS.LIST>
      <TAXBILLALLOCATIONS.LIST></TAXBILLALLOCATIONS.LIST>
      <TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST>
      <TDSEXPENSEALLOCATIONS.LIST></TDSEXPENSEALLOCATIONS.LIST>
      <VATSTATUTORYDETAILS.LIST></VATSTATUTORYDETAILS.LIST>
      <COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST>
      <REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST>
      <INVOICEWISEDETAILS.LIST></INVOICEWISEDETAILS.LIST>
      <VATITCDETAILS.LIST></VATITCDETAILS.LIST>
      <ADVANCETAXDETAILS.LIST></ADVANCETAXDETAILS.LIST>
      <TAXTYPEALLOCATIONS.LIST></TAXTYPEALLOCATIONS.LIST>
    </LEDGERENTRIES.LIST>
  </VOUCHER>
  <VOUCHER
    REMOTEID="650c1f01-8c14-4266-9e96-0a64deb63c1a"
    VCHKEY="a282ccd7-4452-4ea6-8468-933b6012dabd-0000b147:000000c8"
    VCHTYPE="Sales"
    ACTION="Create"
    OBJVIEW="Invoice Voucher View"
  >
    <OLDAUDITENTRYIDS.LIST TYPE="Number">
      <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
    </OLDAUDITENTRYIDS.LIST>
    <DATE>20240929</DATE>
    <VCHSTATUSDATE>20240929</VCHSTATUSDATE>
    <GUID>650c1f01-8c14-4266-9e96-0a64deb63c1a</GUID>
    <GSTREGISTRATIONTYPE>Regular</GSTREGISTRATIONTYPE>
    <VATDEALERTYPE>Regular</VATDEALERTYPE>
    <STATENAME>Gujarat</STATENAME>
    <COUNTRYOFRESIDENCE>India</COUNTRYOFRESIDENCE>
    <PLACEOFSUPPLY>Gujarat</PLACEOFSUPPLY>
    <PARTYNAME>Prime</PARTYNAME>
    <GSTREGISTRATION TAXTYPE="GST" TAXREGISTRATION="">
      Gujarat Registration
    </GSTREGISTRATION>
    <VOUCHERTYPENAME>Sales</VOUCHERTYPENAME>
    <PARTYLEDGERNAME>Prime</PARTYLEDGERNAME>
    <VOUCHERNUMBER>30</VOUCHERNUMBER>
    <BASICBUYERNAME>Prime</BASICBUYERNAME>
    <CMPGSTREGISTRATIONTYPE>Regular</CMPGSTREGISTRATIONTYPE>
    <PARTYMAILINGNAME>Prime</PARTYMAILINGNAME>
    <CONSIGNEEMAILINGNAME>Prime</CONSIGNEEMAILINGNAME>
    <CONSIGNEESTATENAME>Gujarat</CONSIGNEESTATENAME>
    <CMPGSTSTATE>Gujarat</CMPGSTSTATE>
    <CONSIGNEECOUNTRYNAME>India</CONSIGNEECOUNTRYNAME>
    <BASICBASEPARTYNAME>Prime</BASICBASEPARTYNAME>
    <NUMBERINGSTYLE>Auto Retain</NUMBERINGSTYLE>
    <CSTFORMISSUETYPE>Not Applicable</CSTFORMISSUETYPE>
    <CSTFORMRECVTYPE>Not Applicable</CSTFORMRECVTYPE>
    <FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
    <PERSISTEDVIEW>Invoice Voucher View</PERSISTEDVIEW>
    <VCHSTATUSTAXADJUSTMENT>Default</VCHSTATUSTAXADJUSTMENT>
    <VCHSTATUSVOUCHERTYPE>Sales</VCHSTATUSVOUCHERTYPE>
    <VCHGSTCLASS>Not Applicable</VCHGSTCLASS>
    <VCHENTRYMODE>Item Invoice</VCHENTRYMODE>
    <ALLINVENTORYENTRIES.LIST>
      <STOCKITEMNAME>Pump</STOCKITEMNAME>
      <GSTOVRDNISREVCHARGEAPPL>Not Applicable</GSTOVRDNISREVCHARGEAPPL>
      <GSTOVRDNSTOREDNATURE></GSTOVRDNSTOREDNATURE>
      <GSTOVRDNTYPEOFSUPPLY>Goods</GSTOVRDNTYPEOFSUPPLY>
      <GSTRATEINFERAPPLICABILITY>
        As per Masters/Company
      </GSTRATEINFERAPPLICABILITY>
      <GSTHSNINFERAPPLICABILITY>
        As per Masters/Company
      </GSTHSNINFERAPPLICABILITY>
      <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
      <RATE>111/nos</RATE>
      <AMOUNT>111</AMOUNT>
      <ACTUALQTY>1 nos</ACTUALQTY>
      <BILLEDQTY>1 nos</BILLEDQTY>
      <BATCHALLOCATIONS.LIST>
        <GODOWNNAME>Main Location</GODOWNNAME>
        <BATCHNAME>Primary Batch</BATCHNAME>
        <TRACKINGNUMBER>Not Applicable</TRACKINGNUMBER>
        <AMOUNT>111</AMOUNT>
        <ACTUALQTY>1 nos</ACTUALQTY>
        <BILLEDQTY>1 nos</BILLEDQTY>
      </BATCHALLOCATIONS.LIST>
      <ACCOUNTINGALLOCATIONS.LIST>
        <LEDGERNAME>Sales Ledger</LEDGERNAME>
        <GSTCLASS>Not Applicable</GSTCLASS>
        <AMOUNT>111</AMOUNT>
      </ACCOUNTINGALLOCATIONS.LIST>
    </ALLINVENTORYENTRIES.LIST>
    <ALLINVENTORYENTRIES.LIST>
      <STOCKITEMNAME>Ro</STOCKITEMNAME>
      <GSTOVRDNISREVCHARGEAPPL>Not Applicable</GSTOVRDNISREVCHARGEAPPL>
      <GSTOVRDNSTOREDNATURE></GSTOVRDNSTOREDNATURE>
      <GSTOVRDNTYPEOFSUPPLY>Goods</GSTOVRDNTYPEOFSUPPLY>
      <GSTRATEINFERAPPLICABILITY>
        As per Masters/Company
      </GSTRATEINFERAPPLICABILITY>
      <GSTHSNINFERAPPLICABILITY>
        As per Masters/Company
      </GSTHSNINFERAPPLICABILITY>
      <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
      <RATE>222/nos</RATE>
      <AMOUNT>444</AMOUNT>
      <ACTUALQTY>2 nos</ACTUALQTY>
      <BILLEDQTY>2 nos</BILLEDQTY>
      <BATCHALLOCATIONS.LIST>
        <GODOWNNAME>Main Location</GODOWNNAME>
        <BATCHNAME>Primary Batch</BATCHNAME>
        <TRACKINGNUMBER>Not Applicable</TRACKINGNUMBER>
        <AMOUNT>444</AMOUNT>
        <ACTUALQTY>2 nos</ACTUALQTY>
        <BILLEDQTY>2 nos</BILLEDQTY>
      </BATCHALLOCATIONS.LIST>
      <ACCOUNTINGALLOCATIONS.LIST>
        <LEDGERNAME>Sales Ledger</LEDGERNAME>
        <GSTCLASS>Not Applicable</GSTCLASS>
        <AMOUNT>444</AMOUNT>
      </ACCOUNTINGALLOCATIONS.LIST>
    </ALLINVENTORYENTRIES.LIST>
    <LEDGERENTRIES.LIST>
      <OLDAUDITENTRYIDS.LIST TYPE="Number">
        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
      </OLDAUDITENTRYIDS.LIST>
      <LEDGERNAME>Prime</LEDGERNAME>
      <GSTCLASS>Not Applicable</GSTCLASS>
      <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
      <LEDGERFROMITEM>No</LEDGERFROMITEM>
      <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
      <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
      <GSTOVERRIDDEN>No</GSTOVERRIDDEN>
      <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
      <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
      <STRDGSTISPARTYLEDGER>No</STRDGSTISPARTYLEDGER>
      <STRDGSTISDUTYLEDGER>No</STRDGSTISDUTYLEDGER>
      <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
      <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
      <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
      <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
      <AMOUNT>-555</AMOUNT>
      <SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST>
      <BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST>
      <BILLALLOCATIONS.LIST>
        <NAME>30</NAME>
        <BILLTYPE>New Ref</BILLTYPE>
        <TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE>
        <AMOUNT>-555</AMOUNT>
        <INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST>
        <STBILLCATEGORIES.LIST></STBILLCATEGORIES.LIST>
      </BILLALLOCATIONS.LIST>
      <INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST>
      <OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST>
      <ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST>
      <AUDITENTRIES.LIST></AUDITENTRIES.LIST>
      <INPUTCRALLOCS.LIST></INPUTCRALLOCS.LIST>
      <DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST>
      <EXCISEDUTYHEADDETAILS.LIST></EXCISEDUTYHEADDETAILS.LIST>
      <RATEDETAILS.LIST></RATEDETAILS.LIST>
      <SUMMARYALLOCS.LIST></SUMMARYALLOCS.LIST>
      <CENVATDUTYALLOCATIONS.LIST></CENVATDUTYALLOCATIONS.LIST>
      <STPYMTDETAILS.LIST></STPYMTDETAILS.LIST>
      <EXCISEPAYMENTALLOCATIONS.LIST></EXCISEPAYMENTALLOCATIONS.LIST>
      <TAXBILLALLOCATIONS.LIST></TAXBILLALLOCATIONS.LIST>
      <TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST>
      <TDSEXPENSEALLOCATIONS.LIST></TDSEXPENSEALLOCATIONS.LIST>
      <VATSTATUTORYDETAILS.LIST></VATSTATUTORYDETAILS.LIST>
      <COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST>
      <REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST>
      <INVOICEWISEDETAILS.LIST></INVOICEWISEDETAILS.LIST>
      <VATITCDETAILS.LIST></VATITCDETAILS.LIST>
      <ADVANCETAXDETAILS.LIST></ADVANCETAXDETAILS.LIST>
      <TAXTYPEALLOCATIONS.LIST></TAXTYPEALLOCATIONS.LIST>
    </LEDGERENTRIES.LIST>
  </VOUCHER>
</TALLYMESSAGE>;
