<TALLYMESSAGE xmlns:UDF="TallyUDF">
  <VOUCHER
    REMOTEID="a282ccd7-4452-4ea6-8468-933b6012dabd-00000024"
    VCHKEY="a282ccd7-4452-4ea6-8468-933b6012dabd-0000b147:000000c8"
    VCHTYPE="Sales"
    ACTION="Create"
    OBJVIEW="Invoice Voucher View"
  >
    <OLDAUDITENTRYIDS.LIST TYPE="Number">
      <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
    </OLDAUDITENTRYIDS.LIST>
    <DATE>20240402</DATE>
    <VCHSTATUSDATE>20240402</VCHSTATUSDATE>
    <GUID>a282ccd7-4452-4ea6-8468-933b6012dabd-00000024</GUID>
    <GSTREGISTRATIONTYPE>Regular</GSTREGISTRATIONTYPE>
    <VATDEALERTYPE>Regular</VATDEALERTYPE>
    <STATENAME>Gujarat</STATENAME>
    <COUNTRYOFRESIDENCE>India</COUNTRYOFRESIDENCE>
    <PLACEOFSUPPLY>Gujarat</PLACEOFSUPPLY>
    <PARTYNAME>${sales.name}</PARTYNAME>
    <GSTREGISTRATION TAXTYPE="GST" TAXREGISTRATION="">
      Gujarat Registration
    </GSTREGISTRATION>
    <VOUCHERTYPENAME>Sales</VOUCHERTYPENAME>
    <PARTYLEDGERNAME>${sales.name}</PARTYLEDGERNAME>
    <VOUCHERNUMBER>30</VOUCHERNUMBER>
    <BASICBUYERNAME>${sales.name}</BASICBUYERNAME>
    <CMPGSTREGISTRATIONTYPE>Regular</CMPGSTREGISTRATIONTYPE>
    <PARTYMAILINGNAME>${sales.name}</PARTYMAILINGNAME>
    <CONSIGNEEMAILINGNAME>${sales.name}</CONSIGNEEMAILINGNAME>
    <CONSIGNEESTATENAME>Gujarat</CONSIGNEESTATENAME>
    <CMPGSTSTATE>Gujarat</CMPGSTSTATE>
    <CONSIGNEECOUNTRYNAME>India</CONSIGNEECOUNTRYNAME>
    <BASICBASEPARTYNAME>${sales.name}</BASICBASEPARTYNAME>
    <NUMBERINGSTYLE>Auto Retain</NUMBERINGSTYLE>
    <CSTFORMISSUETYPE>&#4; Not Applicable</CSTFORMISSUETYPE>
    <CSTFORMRECVTYPE>&#4; Not Applicable</CSTFORMRECVTYPE>
    <FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
    <PERSISTEDVIEW>Invoice Voucher View</PERSISTEDVIEW>
    <VCHSTATUSTAXADJUSTMENT>Default</VCHSTATUSTAXADJUSTMENT>
    <VCHSTATUSVOUCHERTYPE>Sales</VCHSTATUSVOUCHERTYPE>
    <VCHSTATUSTAXUNIT>Gujarat Registration</VCHSTATUSTAXUNIT>
    <VCHGSTCLASS>&#4; Not Applicable</VCHGSTCLASS>
    <VCHENTRYMODE>Item Invoice</VCHENTRYMODE>
    <DIFFACTUALQTY>No</DIFFACTUALQTY>
    <ISMSTFROMSYNC>No</ISMSTFROMSYNC>
    <ISDELETED>No</ISDELETED>
    <ISSECURITYONWHENENTERED>No</ISSECURITYONWHENENTERED>
    <ASORIGINAL>No</ASORIGINAL>
    <AUDITED>No</AUDITED>
    <ISCOMMONPARTY>No</ISCOMMONPARTY>
    <FORJOBCOSTING>No</FORJOBCOSTING>
    <ISOPTIONAL>No</ISOPTIONAL>
    <EFFECTIVEDATE>20240402</EFFECTIVEDATE>
    <USEFOREXCISE>No</USEFOREXCISE>
    <ISFORJOBWORKIN>No</ISFORJOBWORKIN>
    <ALLOWCONSUMPTION>No</ALLOWCONSUMPTION>
    <USEFORINTEREST>No</USEFORINTEREST>
    <USEFORGAINLOSS>No</USEFORGAINLOSS>
    <USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>
    <USEFORCOMPOUND>No</USEFORCOMPOUND>
    <USEFORSERVICETAX>No</USEFORSERVICETAX>
    <ISREVERSECHARGEAPPLICABLE>No</ISREVERSECHARGEAPPLICABLE>
    <ISSYSTEM>No</ISSYSTEM>
    <ISFETCHEDONLY>No</ISFETCHEDONLY>
    <ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>
    <ISCANCELLED>No</ISCANCELLED>
    <ISONHOLD>No</ISONHOLD>
    <ISSUMMARY>No</ISSUMMARY>
    <ISECOMMERCESUPPLY>No</ISECOMMERCESUPPLY>
    <ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE>
    <ISGSTSECSEVENAPPLICABLE>No</ISGSTSECSEVENAPPLICABLE>
    <IGNOREEINVVALIDATION>No</IGNOREEINVVALIDATION>
    <CMPGSTISOTHTERRITORYASSESSEE>No</CMPGSTISOTHTERRITORYASSESSEE>
    <PARTYGSTISOTHTERRITORYASSESSEE>No</PARTYGSTISOTHTERRITORYASSESSEE>
    <IRNJSONEXPORTED>No</IRNJSONEXPORTED>
    <IRNCANCELLED>No</IRNCANCELLED>
    <IGNOREGSTCONFLICTINMIG>No</IGNOREGSTCONFLICTINMIG>
    <ISOPBALTRANSACTION>No</ISOPBALTRANSACTION>
    <IGNOREGSTFORMATVALIDATION>No</IGNOREGSTFORMATVALIDATION>
    <ISELIGIBLEFORITC>Yes</ISELIGIBLEFORITC>
    <UPDATESUMMARYVALUES>No</UPDATESUMMARYVALUES>
    <ISEWAYBILLAPPLICABLE>No</ISEWAYBILLAPPLICABLE>
    <ISDELETEDRETAINED>No</ISDELETEDRETAINED>
    <ISNULL>No</ISNULL>
    <ISEXCISEVOUCHER>No</ISEXCISEVOUCHER>
    <EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>
    <USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER>
    <ISEXER1NOPOVERWRITE>No</ISEXER1NOPOVERWRITE>
    <ISEXF2NOPOVERWRITE>No</ISEXF2NOPOVERWRITE>
    <ISEXER3NOPOVERWRITE>No</ISEXER3NOPOVERWRITE>
    <IGNOREPOSVALIDATION>No</IGNOREPOSVALIDATION>
    <EXCISEOPENING>No</EXCISEOPENING>
    <USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION>
    <ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>
    <ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>
    <ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH>
    <INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH>
    <ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT>
    <ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>
    <IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE>
    <ISVATPAIDATCUSTOMS>No</ISVATPAIDATCUSTOMS>
    <ISDECLAREDTOCUSTOMS>No</ISDECLAREDTOCUSTOMS>
    <VATADVANCEPAYMENT>No</VATADVANCEPAYMENT>
    <VATADVPAY>No</VATADVPAY>
    <ISCSTDELCAREDGOODSSALES>No</ISCSTDELCAREDGOODSSALES>
    <ISVATRESTAXINV>No</ISVATRESTAXINV>
    <ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>
    <ISISDVOUCHER>No</ISISDVOUCHER>
    <ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>
    <ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH>
    <GSTNOTEXPORTED>No</GSTNOTEXPORTED>
    <IGNOREGSTINVALIDATION>No</IGNOREGSTINVALIDATION>
    <ISGSTREFUND>No</ISGSTREFUND>
    <OVRDNEWAYBILLAPPLICABILITY>No</OVRDNEWAYBILLAPPLICABILITY>
    <ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT>
    <VCHSTATUSISVCHNUMUSED>No</VCHSTATUSISVCHNUMUSED>
    <VCHGSTSTATUSISINCLUDED>No</VCHGSTSTATUSISINCLUDED>
    <VCHGSTSTATUSISUNCERTAIN>Yes</VCHGSTSTATUSISUNCERTAIN>
    <VCHGSTSTATUSISEXCLUDED>No</VCHGSTSTATUSISEXCLUDED>
    <VCHGSTSTATUSISAPPLICABLE>Yes</VCHGSTSTATUSISAPPLICABLE>
    <VCHGSTSTATUSISGSTR2BRECONCILED>No</VCHGSTSTATUSISGSTR2BRECONCILED>
    <VCHGSTSTATUSISGSTR2BONLYINPORTAL>No</VCHGSTSTATUSISGSTR2BONLYINPORTAL>
    <VCHGSTSTATUSISGSTR2BONLYINBOOKS>No</VCHGSTSTATUSISGSTR2BONLYINBOOKS>
    <VCHGSTSTATUSISGSTR2BMISMATCH>No</VCHGSTSTATUSISGSTR2BMISMATCH>
    <VCHGSTSTATUSISGSTR2BINDIFFPERIOD>No</VCHGSTSTATUSISGSTR2BINDIFFPERIOD>
    <VCHGSTSTATUSISRETEFFDATEOVERRDN>No</VCHGSTSTATUSISRETEFFDATEOVERRDN>
    <VCHGSTSTATUSISOVERRDN>No</VCHGSTSTATUSISOVERRDN>
    <VCHGSTSTATUSISSTATINDIFFDATE>No</VCHGSTSTATUSISSTATINDIFFDATE>
    <VCHGSTSTATUSISRETINDIFFDATE>No</VCHGSTSTATUSISRETINDIFFDATE>
    <VCHGSTSTATUSMAINSECTIONEXCLUDED>No</VCHGSTSTATUSMAINSECTIONEXCLUDED>
    <VCHGSTSTATUSISBRANCHTRANSFEROUT>No</VCHGSTSTATUSISBRANCHTRANSFEROUT>
    <VCHGSTSTATUSISSYSTEMSUMMARY>No</VCHGSTSTATUSISSYSTEMSUMMARY>
    <VCHSTATUSISUNREGISTEREDRCM>No</VCHSTATUSISUNREGISTEREDRCM>
    <VCHSTATUSISOPTIONAL>No</VCHSTATUSISOPTIONAL>
    <VCHSTATUSISCANCELLED>No</VCHSTATUSISCANCELLED>
    <VCHSTATUSISDELETED>No</VCHSTATUSISDELETED>
    <VCHSTATUSISOPENINGBALANCE>No</VCHSTATUSISOPENINGBALANCE>
    <VCHSTATUSISFETCHEDONLY>No</VCHSTATUSISFETCHEDONLY>
    <PAYMENTLINKHASMULTIREF>No</PAYMENTLINKHASMULTIREF>
    <ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE>
    <ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS>
    <ISDESIGNATEDZONEPARTY>No</ISDESIGNATEDZONEPARTY>
    <HASCASHFLOW>No</HASCASHFLOW>
    <ISPOSTDATED>No</ISPOSTDATED>
    <USETRACKINGNUMBER>No</USETRACKINGNUMBER>
    <ISINVOICE>Yes</ISINVOICE>
    <MFGJOURNAL>No</MFGJOURNAL>
    <HASDISCOUNTS>No</HASDISCOUNTS>
    <ASPAYSLIP>No</ASPAYSLIP>
    <ISCOSTCENTRE>No</ISCOSTCENTRE>
    <ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>
    <ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON>
    <ISBLANKCHEQUE>No</ISBLANKCHEQUE>
    <ISVOID>No</ISVOID>
    <ORDERLINESTATUS>No</ORDERLINESTATUS>
    <VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES>
    <VATISPURCEXEMPTED>No</VATISPURCEXEMPTED>
    <ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE>
    <VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH>
    <ISVATDUTYPAID>Yes</ISVATDUTYPAID>
    <ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE>
    <ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR>
    <ISDELETEDVCHRETAINED>No</ISDELETEDVCHRETAINED>
    <CHANGEVCHMODE>No</CHANGEVCHMODE>
    <RESETIRNQRCODE>No</RESETIRNQRCODE>
    <ALTERID> 40</ALTERID>
    <MASTERID> 36</MASTERID>
    <VOUCHERKEY>194918500794568</VOUCHERKEY>
    <VOUCHERRETAINKEY>117</VOUCHERRETAINKEY>
    <VOUCHERNUMBERSERIES>Default</VOUCHERNUMBERSERIES>
    <EWAYBILLDETAILS.LIST> </EWAYBILLDETAILS.LIST>
    <EXCLUDEDTAXATIONS.LIST> </EXCLUDEDTAXATIONS.LIST>
    <OLDAUDITENTRIES.LIST> </OLDAUDITENTRIES.LIST>
    <ACCOUNTAUDITENTRIES.LIST> </ACCOUNTAUDITENTRIES.LIST>
    <AUDITENTRIES.LIST> </AUDITENTRIES.LIST>
    <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
    <GSTADVADJDETAILS.LIST> </GSTADVADJDETAILS.LIST>
    <ALLINVENTORYENTRIES.LIST>
      <STOCKITEMNAME>${sales.products[0].product}</STOCKITEMNAME>
      <GSTOVRDNISREVCHARGEAPPL>&#4; Not Applicable</GSTOVRDNISREVCHARGEAPPL>
      <GSTOVRDNSTOREDNATURE />
      <GSTOVRDNTYPEOFSUPPLY>Goods</GSTOVRDNTYPEOFSUPPLY>
      <GSTRATEINFERAPPLICABILITY>
        As per Masters/Company
      </GSTRATEINFERAPPLICABILITY>
      <GSTHSNINFERAPPLICABILITY>
        As per Masters/Company
      </GSTHSNINFERAPPLICABILITY>
      <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
      <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
      <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
      <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
      <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
      <ISAUTONEGATE>No</ISAUTONEGATE>
      <ISCUSTOMSCLEARANCE>No</ISCUSTOMSCLEARANCE>
      <ISTRACKCOMPONENT>No</ISTRACKCOMPONENT>
      <ISTRACKPRODUCTION>No</ISTRACKPRODUCTION>
      <ISPRIMARYITEM>No</ISPRIMARYITEM>
      <ISSCRAP>No</ISSCRAP>
      <RATE>${sales.products[0].price}/nos</RATE>
      <AMOUNT>${sales.products[0].subtotal}</AMOUNT>
      <ACTUALQTY> ${sales.products[0].qty} nos</ACTUALQTY>
      <BILLEDQTY> ${sales.products[0].qty} nos</BILLEDQTY>
      <BATCHALLOCATIONS.LIST>
        <GODOWNNAME>Main Location</GODOWNNAME>
        <BATCHNAME>Primary Batch</BATCHNAME>
        <INDENTNO>&#4; Not Applicable</INDENTNO>
        <ORDERNO>&#4; Not Applicable</ORDERNO>
        <TRACKINGNUMBER>&#4; Not Applicable</TRACKINGNUMBER>
        <DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>
        <AMOUNT>${sales.products[0].subtotal}</AMOUNT>
        <ACTUALQTY> ${sales.products[0].qty} nos</ACTUALQTY>
        <BILLEDQTY> ${sales.products[0].qty} nos</BILLEDQTY>
        <ADDITIONALDETAILS.LIST> </ADDITIONALDETAILS.LIST>
        <VOUCHERCOMPONENTLIST.LIST> </VOUCHERCOMPONENTLIST.LIST>
      </BATCHALLOCATIONS.LIST>
      <ACCOUNTINGALLOCATIONS.LIST>
        <OLDAUDITENTRYIDS.LIST TYPE="Number">
          <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
        </OLDAUDITENTRYIDS.LIST>
        <LEDGERNAME>Sales Ledger</LEDGERNAME>
        <GSTCLASS>&#4; Not Applicable</GSTCLASS>
        <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
        <LEDGERFROMITEM>No</LEDGERFROMITEM>
        <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
        <ISPARTYLEDGER>No</ISPARTYLEDGER>
        <GSTOVERRIDDEN>No</GSTOVERRIDDEN>
        <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
        <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
        <STRDGSTISPARTYLEDGER>No</STRDGSTISPARTYLEDGER>
        <STRDGSTISDUTYLEDGER>No</STRDGSTISDUTYLEDGER>
        <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
        <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
        <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
        <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
        <AMOUNT>${sales.products[0].subtotal}</AMOUNT>
        <SERVICETAXDETAILS.LIST> </SERVICETAXDETAILS.LIST>
        <BANKALLOCATIONS.LIST> </BANKALLOCATIONS.LIST>
        <BILLALLOCATIONS.LIST> </BILLALLOCATIONS.LIST>
        <INTERESTCOLLECTION.LIST> </INTERESTCOLLECTION.LIST>
        <OLDAUDITENTRIES.LIST> </OLDAUDITENTRIES.LIST>
        <ACCOUNTAUDITENTRIES.LIST> </ACCOUNTAUDITENTRIES.LIST>
        <AUDITENTRIES.LIST> </AUDITENTRIES.LIST>
        <INPUTCRALLOCS.LIST> </INPUTCRALLOCS.LIST>
        <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
        <EXCISEDUTYHEADDETAILS.LIST> </EXCISEDUTYHEADDETAILS.LIST>
        <RATEDETAILS.LIST> </RATEDETAILS.LIST>
        <SUMMARYALLOCS.LIST> </SUMMARYALLOCS.LIST>
        <CENVATDUTYALLOCATIONS.LIST> </CENVATDUTYALLOCATIONS.LIST>
        <STPYMTDETAILS.LIST> </STPYMTDETAILS.LIST>
        <EXCISEPAYMENTALLOCATIONS.LIST> </EXCISEPAYMENTALLOCATIONS.LIST>
        <TAXBILLALLOCATIONS.LIST> </TAXBILLALLOCATIONS.LIST>
        <TAXOBJECTALLOCATIONS.LIST> </TAXOBJECTALLOCATIONS.LIST>
        <TDSEXPENSEALLOCATIONS.LIST> </TDSEXPENSEALLOCATIONS.LIST>
        <VATSTATUTORYDETAILS.LIST> </VATSTATUTORYDETAILS.LIST>
        <COSTTRACKALLOCATIONS.LIST> </COSTTRACKALLOCATIONS.LIST>
        <REFVOUCHERDETAILS.LIST> </REFVOUCHERDETAILS.LIST>
        <INVOICEWISEDETAILS.LIST> </INVOICEWISEDETAILS.LIST>
        <VATITCDETAILS.LIST> </VATITCDETAILS.LIST>
        <ADVANCETAXDETAILS.LIST> </ADVANCETAXDETAILS.LIST>
        <TAXTYPEALLOCATIONS.LIST> </TAXTYPEALLOCATIONS.LIST>
      </ACCOUNTINGALLOCATIONS.LIST>
      <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
      <RATEDETAILS.LIST>
        <GSTRATEDUTYHEAD>CGST</GSTRATEDUTYHEAD>
      </RATEDETAILS.LIST>
      <RATEDETAILS.LIST>
        <GSTRATEDUTYHEAD>SGST/UTGST</GSTRATEDUTYHEAD>
      </RATEDETAILS.LIST>
      <RATEDETAILS.LIST>
        <GSTRATEDUTYHEAD>IGST</GSTRATEDUTYHEAD>
      </RATEDETAILS.LIST>
      <RATEDETAILS.LIST>
        <GSTRATEDUTYHEAD>Cess</GSTRATEDUTYHEAD>
      </RATEDETAILS.LIST>
      <RATEDETAILS.LIST>
        <GSTRATEDUTYHEAD>State Cess</GSTRATEDUTYHEAD>
      </RATEDETAILS.LIST>
      <SUPPLEMENTARYDUTYHEADDETAILS.LIST> </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
      <TAXOBJECTALLOCATIONS.LIST> </TAXOBJECTALLOCATIONS.LIST>
      <REFVOUCHERDETAILS.LIST> </REFVOUCHERDETAILS.LIST>
      <EXCISEALLOCATIONS.LIST> </EXCISEALLOCATIONS.LIST>
      <EXPENSEALLOCATIONS.LIST> </EXPENSEALLOCATIONS.LIST>
    </ALLINVENTORYENTRIES.LIST>
    <ALLINVENTORYENTRIES.LIST>
      <STOCKITEMNAME>${sales.products[1].product}</STOCKITEMNAME>
      <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
      <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
      <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
      <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
      <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
      <ISAUTONEGATE>No</ISAUTONEGATE>
      <ISCUSTOMSCLEARANCE>No</ISCUSTOMSCLEARANCE>
      <ISTRACKCOMPONENT>No</ISTRACKCOMPONENT>
      <ISTRACKPRODUCTION>No</ISTRACKPRODUCTION>
      <ISPRIMARYITEM>No</ISPRIMARYITEM>
      <ISSCRAP>No</ISSCRAP>
      <RATE>${sales.products[1].price}/nos</RATE>
      <AMOUNT>${sales.products[1].subtotal}</AMOUNT>
      <ACTUALQTY> ${sales.products[1].qty} nos</ACTUALQTY>
      <BILLEDQTY> ${sales.products[1].qty} nos</BILLEDQTY>
      <BATCHALLOCATIONS.LIST>
        <GODOWNNAME>Main Location</GODOWNNAME>
        <BATCHNAME>Primary Batch</BATCHNAME>
        <INDENTNO>&#4; Not Applicable</INDENTNO>
        <ORDERNO>&#4; Not Applicable</ORDERNO>
        <TRACKINGNUMBER>&#4; Not Applicable</TRACKINGNUMBER>
        <DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>
        <AMOUNT>${sales.products[1].subtotal}</AMOUNT>
        <ACTUALQTY> ${sales.products[1].qty} nos</ACTUALQTY>
        <BILLEDQTY> ${sales.products[1].qty} nos</BILLEDQTY>
        <ADDITIONALDETAILS.LIST> </ADDITIONALDETAILS.LIST>
        <VOUCHERCOMPONENTLIST.LIST> </VOUCHERCOMPONENTLIST.LIST>
      </BATCHALLOCATIONS.LIST>
      <ACCOUNTINGALLOCATIONS.LIST>
        <OLDAUDITENTRYIDS.LIST TYPE="Number">
          <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
        </OLDAUDITENTRYIDS.LIST>
        <LEDGERNAME>Sales Ledger</LEDGERNAME>
        <GSTCLASS>&#4; Not Applicable</GSTCLASS>
        <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
        <LEDGERFROMITEM>No</LEDGERFROMITEM>
        <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
        <ISPARTYLEDGER>No</ISPARTYLEDGER>
        <GSTOVERRIDDEN>No</GSTOVERRIDDEN>
        <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
        <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
        <STRDGSTISPARTYLEDGER>No</STRDGSTISPARTYLEDGER>
        <STRDGSTISDUTYLEDGER>No</STRDGSTISDUTYLEDGER>
        <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
        <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
        <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
        <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
        <AMOUNT>${sales.products[1].subtotal}</AMOUNT>
        <SERVICETAXDETAILS.LIST> </SERVICETAXDETAILS.LIST>
        <BANKALLOCATIONS.LIST> </BANKALLOCATIONS.LIST>
        <BILLALLOCATIONS.LIST> </BILLALLOCATIONS.LIST>
        <INTERESTCOLLECTION.LIST> </INTERESTCOLLECTION.LIST>
        <OLDAUDITENTRIES.LIST> </OLDAUDITENTRIES.LIST>
        <ACCOUNTAUDITENTRIES.LIST> </ACCOUNTAUDITENTRIES.LIST>
        <AUDITENTRIES.LIST> </AUDITENTRIES.LIST>
        <INPUTCRALLOCS.LIST> </INPUTCRALLOCS.LIST>
        <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
        <EXCISEDUTYHEADDETAILS.LIST> </EXCISEDUTYHEADDETAILS.LIST>
        <RATEDETAILS.LIST> </RATEDETAILS.LIST>
        <SUMMARYALLOCS.LIST> </SUMMARYALLOCS.LIST>
        <CENVATDUTYALLOCATIONS.LIST> </CENVATDUTYALLOCATIONS.LIST>
        <STPYMTDETAILS.LIST> </STPYMTDETAILS.LIST>
        <EXCISEPAYMENTALLOCATIONS.LIST> </EXCISEPAYMENTALLOCATIONS.LIST>
        <TAXBILLALLOCATIONS.LIST> </TAXBILLALLOCATIONS.LIST>
        <TAXOBJECTALLOCATIONS.LIST> </TAXOBJECTALLOCATIONS.LIST>
        <TDSEXPENSEALLOCATIONS.LIST> </TDSEXPENSEALLOCATIONS.LIST>
        <VATSTATUTORYDETAILS.LIST> </VATSTATUTORYDETAILS.LIST>
        <COSTTRACKALLOCATIONS.LIST> </COSTTRACKALLOCATIONS.LIST>
        <REFVOUCHERDETAILS.LIST> </REFVOUCHERDETAILS.LIST>
        <INVOICEWISEDETAILS.LIST> </INVOICEWISEDETAILS.LIST>
        <VATITCDETAILS.LIST> </VATITCDETAILS.LIST>
        <ADVANCETAXDETAILS.LIST> </ADVANCETAXDETAILS.LIST>
        <TAXTYPEALLOCATIONS.LIST> </TAXTYPEALLOCATIONS.LIST>
      </ACCOUNTINGALLOCATIONS.LIST>
      <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
      <RATEDETAILS.LIST> </RATEDETAILS.LIST>
      <SUPPLEMENTARYDUTYHEADDETAILS.LIST> </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
      <TAXOBJECTALLOCATIONS.LIST> </TAXOBJECTALLOCATIONS.LIST>
      <REFVOUCHERDETAILS.LIST> </REFVOUCHERDETAILS.LIST>
      <EXCISEALLOCATIONS.LIST> </EXCISEALLOCATIONS.LIST>
      <EXPENSEALLOCATIONS.LIST> </EXPENSEALLOCATIONS.LIST>
    </ALLINVENTORYENTRIES.LIST>
    <CONTRITRANS.LIST> </CONTRITRANS.LIST>
    <EWAYBILLERRORLIST.LIST> </EWAYBILLERRORLIST.LIST>
    <IRNERRORLIST.LIST> </IRNERRORLIST.LIST>
    <HARYANAVAT.LIST> </HARYANAVAT.LIST>
    <SUPPLEMENTARYDUTYHEADDETAILS.LIST> </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
    <INVOICEDELNOTES.LIST> </INVOICEDELNOTES.LIST>
    <INVOICEORDERLIST.LIST> </INVOICEORDERLIST.LIST>
    <INVOICEINDENTLIST.LIST> </INVOICEINDENTLIST.LIST>
    <ATTENDANCEENTRIES.LIST> </ATTENDANCEENTRIES.LIST>
    <ORIGINVOICEDETAILS.LIST> </ORIGINVOICEDETAILS.LIST>
    <INVOICEEXPORTLIST.LIST> </INVOICEEXPORTLIST.LIST>
    <LEDGERENTRIES.LIST>
      <OLDAUDITENTRYIDS.LIST TYPE="Number">
        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
      </OLDAUDITENTRYIDS.LIST>
      <LEDGERNAME>${sales.name}</LEDGERNAME>
      <GSTCLASS>&#4; Not Applicable</GSTCLASS>
      <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
      <LEDGERFROMITEM>No</LEDGERFROMITEM>
      <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
      <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
      <GSTOVERRIDDEN>No</GSTOVERRIDDEN>
      <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
      <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
      <STRDGSTISPARTYLEDGER>No</STRDGSTISPARTYLEDGER>
      <STRDGSTISDUTYLEDGER>No</STRDGSTISDUTYLEDGER>
      <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
      <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
      <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
      <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
      <AMOUNT>-${sales.total}</AMOUNT>
      <SERVICETAXDETAILS.LIST> </SERVICETAXDETAILS.LIST>
      <BANKALLOCATIONS.LIST> </BANKALLOCATIONS.LIST>
      <BILLALLOCATIONS.LIST>
        <NAME>30</NAME>
        <BILLTYPE>New Ref</BILLTYPE>
        <TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE>
        <AMOUNT>-${sales.total}</AMOUNT>
        <INTERESTCOLLECTION.LIST> </INTERESTCOLLECTION.LIST>
        <STBILLCATEGORIES.LIST> </STBILLCATEGORIES.LIST>
      </BILLALLOCATIONS.LIST>
      <INTERESTCOLLECTION.LIST> </INTERESTCOLLECTION.LIST>
      <OLDAUDITENTRIES.LIST> </OLDAUDITENTRIES.LIST>
      <ACCOUNTAUDITENTRIES.LIST> </ACCOUNTAUDITENTRIES.LIST>
      <AUDITENTRIES.LIST> </AUDITENTRIES.LIST>
      <INPUTCRALLOCS.LIST> </INPUTCRALLOCS.LIST>
      <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
      <EXCISEDUTYHEADDETAILS.LIST> </EXCISEDUTYHEADDETAILS.LIST>
      <RATEDETAILS.LIST> </RATEDETAILS.LIST>
      <SUMMARYALLOCS.LIST> </SUMMARYALLOCS.LIST>
      <CENVATDUTYALLOCATIONS.LIST> </CENVATDUTYALLOCATIONS.LIST>
      <STPYMTDETAILS.LIST> </STPYMTDETAILS.LIST>
      <EXCISEPAYMENTALLOCATIONS.LIST> </EXCISEPAYMENTALLOCATIONS.LIST>
      <TAXBILLALLOCATIONS.LIST> </TAXBILLALLOCATIONS.LIST>
      <TAXOBJECTALLOCATIONS.LIST> </TAXOBJECTALLOCATIONS.LIST>
      <TDSEXPENSEALLOCATIONS.LIST> </TDSEXPENSEALLOCATIONS.LIST>
      <VATSTATUTORYDETAILS.LIST> </VATSTATUTORYDETAILS.LIST>
      <COSTTRACKALLOCATIONS.LIST> </COSTTRACKALLOCATIONS.LIST>
      <REFVOUCHERDETAILS.LIST> </REFVOUCHERDETAILS.LIST>
      <INVOICEWISEDETAILS.LIST> </INVOICEWISEDETAILS.LIST>
      <VATITCDETAILS.LIST> </VATITCDETAILS.LIST>
      <ADVANCETAXDETAILS.LIST> </ADVANCETAXDETAILS.LIST>
      <TAXTYPEALLOCATIONS.LIST> </TAXTYPEALLOCATIONS.LIST>
    </LEDGERENTRIES.LIST>
    <GST.LIST> </GST.LIST>
    <STKJRNLADDLCOSTDETAILS.LIST> </STKJRNLADDLCOSTDETAILS.LIST>
    <PAYROLLMODEOFPAYMENT.LIST> </PAYROLLMODEOFPAYMENT.LIST>
    <ATTDRECORDS.LIST> </ATTDRECORDS.LIST>
    <GSTEWAYCONSIGNORADDRESS.LIST> </GSTEWAYCONSIGNORADDRESS.LIST>
    <GSTEWAYCONSIGNEEADDRESS.LIST> </GSTEWAYCONSIGNEEADDRESS.LIST>
    <TEMPGSTRATEDETAILS.LIST> </TEMPGSTRATEDETAILS.LIST>
    <TEMPGSTADVADJUSTED.LIST> </TEMPGSTADVADJUSTED.LIST>
  </VOUCHER>
</TALLYMESSAGE>;

// my LS set Voucher layout

<ENVELOPE>
  <HEADER>
    <TALLYREQUEST>Import Data</TALLYREQUEST>
  </HEADER>
  <BODY>
    <IMPORTDATA>
      <REQUESTDESC>
        <REPORTNAME>All Masters</REPORTNAME>
        <STATICVARIABLES>
          <SVCURRENTCOMPANY>My Company</SVCURRENTCOMPANY>
        </STATICVARIABLES>
      </REQUESTDESC>
      <REQUESTDATA>
        <TALLYMESSAGE xmlns:UDF="TallyUDF">
          <VOUCHER>
            <DATE>2024-09-09</DATE>
            <GUID>de117bd9-fe78-493b-91c7-85d6a12a3a0e</GUID>
            <GSTREGISTRATIONTYPE>Regular</GSTREGISTRATIONTYPE>
            <GSTNATUREOFSALE>Inter State</GSTNATUREOFSALE>
            <GSTPARTYTYPE>Regular</GSTPARTYTYPE>
            <UDF:GSTRETURNTYPE>Regular</UDF:GSTRETURNTYPE>
            <UDF:CONSULIEERGOODS>No</UDF:CONSULIEERGOODS>
            <VCHENTRYMODE>Item Invoice</VCHENTRYMODE>
            <ITEMNAME>Ro Pump</ITEMNAME>
            <CATEGORYNAME>Sales</CATEGORYNAME>
            <GSTCLASS>Regular</GSTCLASS>
            <GSTEXEMPT>No</GSTEXEMPT>
            <BATCHNAME>Ro Pump-2024</BATCHNAME>
            <EXPIRYPERIOD>Default</EXPIRYPERIOD>
            <QUANTITY>11</QUANTITY>
            <RATE>13456</RATE>
            <AMOUNT>148016</AMOUNT>
          </VOUCHER>
        </TALLYMESSAGE>
        <TALLYMESSAGE xmlns:UDF="TallyUDF">
          <VOUCHER>
            <DATE>2024-09-22</DATE>
            <GUID>b14b728c-c51c-4120-9b47-12ad42fd1a3f</GUID>
            <GSTREGISTRATIONTYPE>Regular</GSTREGISTRATIONTYPE>
            <GSTNATUREOFSALE>Inter State</GSTNATUREOFSALE>
            <GSTPARTYTYPE>Regular</GSTPARTYTYPE>
            <UDF:GSTRETURNTYPE>Regular</UDF:GSTRETURNTYPE>
            <UDF:CONSULIEERGOODS>No</UDF:CONSULIEERGOODS>
            <VCHENTRYMODE>Item Invoice</VCHENTRYMODE>
            <ITEMNAME>Cartig Ro</ITEMNAME>
            <CATEGORYNAME>Sales</CATEGORYNAME>
            <GSTCLASS>Regular</GSTCLASS>
            <GSTEXEMPT>No</GSTEXEMPT>
            <BATCHNAME>Membrane-2024</BATCHNAME>
            <EXPIRYPERIOD>Default</EXPIRYPERIOD>
            <QUANTITY>555</QUANTITY>
            <RATE>5</RATE>
            <AMOUNT>2775</AMOUNT>
          </VOUCHER>
        </TALLYMESSAGE>
      </REQUESTDATA>
    </IMPORTDATA>
  </BODY>
</ENVELOPE>;
